const KEY='tidal-survival-v2';
const defaultState={island:0,coins:12,stamina:8,maxStamina:8,fish:{沙丁鱼:0,银纹鱼:0,海鳗:0,雷纹鲹:0,灯笼鱼:0},items:{木料:0,绳索:0,淡水:1,鱼饵:3},rod:0,caught:{},day:1,ads:0,won:[],ending:false};
let S;try{S={...defaultState,...JSON.parse(localStorage.getItem(KEY)||'{}')};S.fish={...defaultState.fish,...S.fish};S.items={...defaultState.items,...S.items}}catch{S={...defaultState}}
let mode='ready',tension=30,progress=0,targetFish='',biteTimer=null,bossRound=0,bossMistakes=0,flopHits=0,flopTimer=null,pendingFish='',pendingShiny=false;
const islands=[{name:'漂木湾',emoji:'🏝️',area:'近海',npc:'阿岚',boss:'断桅巨鲨',desc:'一座安静的小岛。阿岚正在修船，缺少木料和绳索。',fish:['沙丁鱼','海鳗','漂流靴']},{name:'雾岬集市',emoji:'🌫️',area:'雾岬海域',npc:'罗叔',boss:'雾影章鱼',desc:'潮沟与礁洞里藏着稀有鱼。渔具匠罗叔能帮你改良钓组。',fish:['银纹鱼','灯笼鱼','海鳗']},{name:'风暴礁',emoji:'🌊',area:'远海',npc:'小满',boss:'风暴海龟',desc:'风暴来临前，先收集雷纹鲹鳞片并校准风向仪。',fish:['雷纹鲹','银纹鱼','灯笼鱼']}];
const fishEmoji={'沙丁鱼':'🐟','银纹鱼':'🐠','海鳗':'🐍','雷纹鲹':'🐡','灯笼鱼':'🏮鱼','漂流靴':'🥾'};
function save(){localStorage.setItem(KEY,JSON.stringify(S));updateUI()}
function updateUI(){document.querySelector('#coins').textContent=S.coins;document.querySelector('#stamina').textContent=S.stamina;document.querySelector('#staminaMax').textContent=S.maxStamina;document.querySelector('#fishCount').textContent=Object.values(S.fish).reduce((a,b)=>a+b,0);document.querySelector('#islandName').textContent=S.ending?'归航港':islands[S.island].name;document.querySelector('#locationTag').textContent=S.ending?'终点海域':islands[S.island].area;document.querySelector('#dayLabel').textContent=`第 ${S.day} 天 · ${['晴','多云','微风','薄雾'][S.day%4]}`;document.querySelector('#rodName').textContent=['旧木鱼竿','耐磨线组','远海钓竿'][Math.min(S.rod,2)];document.querySelector('#bossLabel').textContent=S.won.includes(S.island)?'航向下一岛':'挑战 Boss';document.querySelector('#bossHint').textContent=S.won.includes(S.island)?'突破海域继续前进':'赢得航路';document.querySelector('#dialog').textContent=S.ending?'救援船已经看见了你的信号。回家的航线就在眼前。':islands[S.island].desc;updateFishUI()}
function updateFishUI(){document.querySelector('#tensionText').textContent=tension;document.querySelector('#tensionMeter').style.width=Math.min(tension,100)+'%';document.querySelector('#catchText').textContent=Math.min(progress,100);document.querySelector('#catchMeter').style.width=Math.min(progress,100)+'%';document.querySelector('#tensionWrap').classList.toggle('hidden',mode!=='fight');document.querySelector('#floatIcon').textContent=mode==='bite'?'❗':mode==='fight'?'🐟':'◉';document.querySelector('#bobber').textContent=mode==='bite'?'❗':'●';document.querySelector('#bobber').style.transform=mode==='bite'?'translateY(6px) scale(1.35)':'';let labels={ready:['礁石间泛起细小的涟漪','鱼线已整理好<br><b>抛下鱼钩，等一尾鱼</b>','抛竿'],flop:['鱼获正在沙滩上蹦跶！','<b>趁海鸥飞来前，快速点三下收进鱼篓</b>','收鱼 0/3'],wait:['饵料正在随潮漂动','海面很安静，再等等…','等鱼咬钩'],bite:['浮漂猛地沉了下去！','<b>有鱼上钩了，快收线！</b>','收线'],fight:['鱼在水下奋力挣扎','<b>看好拉力，收线或松线</b>','收线'],result:['鱼获已收入背包','<b>再抛一竿，继续探索</b>','继续钓鱼'],tired:['体力不足','<b>休息一下，或者领取应急补给</b>','休息']};let x=labels[mode];document.querySelector('#activityTitle').textContent=mode==='fight'?'稳住鱼线':mode==='bite'?'鱼咬钩了！':'礁石边垂钓';document.querySelector('#fishStatus').innerHTML=x[1];document.querySelector('#fishAction').textContent=mode==='flop'?`收鱼 ${flopHits}/3`:x[2];document.querySelector('#actionHint').textContent=mode==='fight'?'拉力高时记得松线':mode==='wait'?'海潮轻轻推着浮漂':mode==='flop'?'手快一点，收网有小费！':'点击开始垂钓';}
function toast(s){const e=document.querySelector('#toast');e.textContent=s;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1900)}
function fishAction(){if(mode==='flop'){flopHits++;document.querySelector('#fishAction').textContent=`收鱼 ${flopHits}/3`;document.querySelector('#fishStatus').innerHTML=`${fishEmoji[pendingFish]||'🐟'} ${pendingFish}${pendingShiny?' · 闪光变种':''}<br><b>${flopHits>=3?'收进鱼篓了！':'还差 '+(3-flopHits)+' 下！'}</b>`;document.querySelector('#bobber').textContent=fishEmoji[pendingFish]||'🐟';document.querySelector('#bobber').style.transform=`translate(${(Math.random()-.5)*24}px,${(Math.random()-.5)*8}px) rotate(${Math.random()*35-17}deg)`;if(flopHits>=3)secureFish();return}if(mode==='ready'||mode==='result'){if(S.stamina<1){mode='tired';updateFishUI();return}S.stamina--;S.day++;mode='wait';let pool=islands[S.island].fish;targetFish=pool[Math.floor(Math.random()*pool.length)];save();updateFishUI();biteTimer=setTimeout(()=>{if(mode==='wait'){mode='bite';updateFishUI();toast('浮漂沉下去了！快收线')}} ,1500+Math.random()*1500);return}if(mode==='wait'){clearTimeout(biteTimer);mode='bite';updateFishUI();toast('鱼咬钩了！');return}if(mode==='bite'){mode='fight';tension=32;progress=0;updateFishUI();return}if(mode==='fight'){tension+=24+Math.floor(Math.random()*6);progress+=35+S.rod*4;if(tension>=82){tension-=26;progress+=7;toast('你松了松鱼线，躲开一次挣脱！')}if(progress>=100){landFish()}else if(tension>=100){mode='result';toast(`${targetFish}挣脱了鱼钩…`);updateFishUI()}else updateFishUI();return}if(mode==='tired'){rest()}}
function releaseLine(){if(mode!=='fight')return;tension=Math.max(18,tension-30);progress+=8;toast('松线缓冲，鱼还在！');if(progress>=100)landFish();else updateFishUI()}
function landFish(){if(targetFish==='漂流靴'){mode='result';S.items.木料++;toast('捞到一只漂流靴，拆出木料×1');save();updateFishUI();return}pendingFish=targetFish;pendingShiny=Math.random()<.08;flopHits=0;mode='flop';document.querySelector('#fishStatus').innerHTML=`${fishEmoji[pendingFish]||'🐟'} ${pendingFish}<br><b>它在沙滩上蹦跶！快点三下收网</b>`;document.querySelector('#actionHint').textContent='收网快手奖励额外金币';updateFishUI();flopTimer=setTimeout(()=>{if(mode==='flop'){mode='result';document.querySelector('#fishStatus').innerHTML='海鸥抢先叼走了鱼！<br><b>下次收线后快点收网</b>';toast('鱼获被海鸥抢走了…');updateFishUI()}},7000)}
function secureFish(){clearTimeout(flopTimer);mode='result';S.fish[pendingFish]=(S.fish[pendingFish]||0)+1;S.caught[pendingFish]=true;if(pendingShiny){S.fish[pendingFish]+=1;S.caught[pendingFish+'·闪光']=true;toast(`漂亮收网！闪光${pendingFish} ×2`)}else{S.coins+=3;toast(`收网成功！${pendingFish} ×1 · 手快小费 +3`)}document.querySelector('#fishStatus').innerHTML=`${fishEmoji[pendingFish]||'🐟'}<br><b>收入鱼篓！去交易换钱或物资</b>`;save();updateFishUI()}
function rest(){S.stamina=S.maxStamina;S.day++;mode='ready';save();toast('在营地休息后，体力恢复了')}
function openSheet(content){document.querySelector('#sheetContent').innerHTML=content;document.querySelector('#overlay').classList.remove('hidden')}
function closeSheet(){document.querySelector('#overlay').classList.add('hidden')}
function overlayClick(e){if(e.target.id==='overlay')closeSheet()}
function row(icon,name,desc,count,button,onclick,disabled=false){return `<div class="item-row"><div class="item-icon">${icon}</div><div class="item-copy"><b>${name}</b><small>${desc}</small></div><span class="count">${count}</span>${button?`<button class="small-action" ${disabled?'disabled':''} onclick='${onclick}'>${button}</button>`:''}</div>`}
function openTrade(){let island=islands[S.island];let sales=Object.entries(S.fish).filter(([,n])=>n>0).map(([f,n])=>row(fishEmoji[f]||'🐟',f+' · 鱼贩收购',`每条 ${({沙丁鱼:5,银纹鱼:9,海鳗:8,雷纹鲹:16,灯笼鱼:13}[f]||5)} 枚金币`, `持有 ${n}`, '卖出 1 条', `sellFish(\"${f}\")`)).join('')||'<p class="sheet-sub">鱼篓是空的。去海边再钓几条吧。</p>';let fishName=S.island===0?'沙丁鱼':S.island===1?'银纹鱼':'雷纹鲹';let canFish=(S.fish[fishName]||0)>=2;let body=`<h2>${islands[S.island].npc}的营地交易</h2><p class="sheet-sub">鱼获可以卖给鱼贩换金币，也可以直接换修船物资。</p><div class="shop-banner"><b>鱼贩收购</b><p>鱼越稀有，收购价越高。留给任务的鱼也可以直接以物易物。</p></div>${sales}<div style="height:8px"></div>${row('🪵','修船木料','沙丁鱼 ×2 可交换木料 ×1',`现有 ${S.items.木料}`,'交换 2 条鱼','tradeFish(\"沙丁鱼\",2,\"木料\",1)',(S.fish['沙丁鱼']||0)<2)}${row('🪢','结实绳索','海鳗 ×1 可交换绳索 ×1',`现有 ${S.items.绳索}`,'交换海鳗','tradeFish("海鳗",1,"绳索",1)',(S.fish['海鳗']||0)<1)}${row('💧','淡水补给','任意鱼 ×1 可兑换淡水 ×1',`现有 ${S.items.淡水}`,'换淡水','tradeAnyFish()',Object.values(S.fish).every(n=>n<1))}${row('🪱','鱼饵','银纹鱼 ×1 可换鱼饵 ×2',`现有 ${S.items.鱼饵}`,'换鱼饵','tradeFish("银纹鱼",1,"鱼饵",2)',(S.fish['银纹鱼']||0)<1)}<button class="sheet-cta secondary" onclick="closeSheet()">先去钓鱼</button>`;openSheet(body)}
function sellFish(f){if((S.fish[f]||0)<1)return;const price=({沙丁鱼:5,银纹鱼:9,海鳗:8,雷纹鲹:16,灯笼鱼:13}[f]||5);S.fish[f]--;S.coins+=price;save();toast(`${f}卖出，获得金币 ×${price}`);openTrade()}
function tradeFish(f,n,item,q){if((S.fish[f]||0)<n)return;S.fish[f]-=n;S.items[item]=(S.items[item]||0)+q;S.coins+=1;save();toast(`交换成功：${item} ×${q}`);openTrade()}
function tradeAnyFish(){let f=Object.keys(S.fish).find(k=>S.fish[k]>0);if(!f)return;tradeFish(f,1,'淡水',1)}
function openInventory(){let caught=Object.entries(S.fish).filter(x=>x[1]>0).map(([n,c])=>`${fishEmoji[n]||'🐟'} ${n} ×${c}`).join('　·　')||'还没有鱼获，去岸边抛一竿吧。';let cost= S.rod===0?{木料:1,绳索:0}:S.rod===1?{木料:2,绳索:1}:null;let gold=S.rod===0?18:42;let need=cost?`${gold} 金币、`+Object.entries(cost).filter(([,v])=>v>0).map(([k,v])=>`${k} ×${v}`).join('、'):'已是最高级鱼竿';openSheet(`<h2>背包与装备</h2><p class="sheet-sub">整理旅途中收集的鱼获和生存物资。</p>${row('🎣',['旧木鱼竿','耐磨线组','远海钓竿'][Math.min(S.rod,2)],S.rod<2?`升级需要：${need}`:'已完成全部鱼竿升级',`Lv.${S.rod+1}`,S.rod<2?'升级鱼竿':'已满级','upgradeRod()',S.rod>=2||S.coins<gold||Object.entries(cost||{}).some(([k,v])=>S.items[k]<v))}${row('🪵','木料','船体修理与工具制作',`×${S.items.木料}`)}${row('🪢','绳索','修船与远航必需物资',`×${S.items.绳索}`)}${row('🪱','鱼饵','钓鱼时消耗，提升咬钩机会',`×${S.items.鱼饵}`)}<div class="item-row" style="display:block"><div class="item-copy"><b>今日鱼获</b><small>${caught}</small></div></div><button class="sheet-cta secondary" onclick="closeSheet()">收好背包</button>`)}
function upgradeRod(){let cost=S.rod===0?{木料:1,绳索:0}:{木料:2,绳索:1};let gold=S.rod===0?18:42;if(S.coins<gold||Object.entries(cost).some(([k,v])=>S.items[k]<v))return;S.coins-=gold;Object.entries(cost).forEach(([k,v])=>S.items[k]-=v);S.rod++;save();toast('鱼竿升级完成！控线更稳了');openInventory()}
function openCollection(){let all=['沙丁鱼','银纹鱼','海鳗','雷纹鲹','灯笼鱼','漂流靴'];let cells=all.map(f=>`<div class="fish-tile ${(S.caught[f]||S.items.木料>0&&f==='漂流靴')?'got':''}"><span>${S.caught[f]?fishEmoji[f]||'🐟':'？'}</span><b>${S.caught[f]?f:'未发现'}</b><small>${S.caught[f]?'已记录':'继续探索海域'}</small></div>`).join('');openSheet(`<h2>海岛鱼类图鉴</h2><p class="sheet-sub">已发现 ${Object.keys(S.caught).length} / ${all.length} 种海洋生物。每座岛都有新的鱼群。</p><div class="fish-grid">${cells}</div><div class="shop-banner"><b>联名渔具档案 <span class="badge">合作展示</span></b><p>真实合作品牌可在此展示产品故事与授权信息。当前原型使用虚拟品牌内容。</p></div><button class="sheet-cta secondary" onclick="closeSheet()">继续探索</button>`)}
function openIslands(){let html=`<h2>群岛航图</h2><p class="sheet-sub">每片海域都藏着新的渔场与守岛巨兽。</p>`+islands.map((it,i)=>{let unlocked=i<=S.island;return `<div class="island-card"><span class="emoji">${it.emoji}</span><div><b>${it.name}</b><small>${it.desc}</small></div><span class="pill ${unlocked?'':'locked'}">${S.won.includes(i)?'已突破':unlocked?'当前海域':'未解锁'}</span></div>`}).join('')+`<button class="sheet-cta secondary" onclick="closeSheet()">回到营地</button>`;openSheet(html)}
function openBoss(){if(S.won.includes(S.island)){if(S.island<2){S.island++;S.stamina=S.maxStamina;S.day++;save();mode='ready';closeSheet();toast(`扬帆出发，抵达${islands[S.island].name}！`);return}S.ending=true;save();closeSheet();openEnding();return}bossRound=0;bossMistakes=0;showBoss()}
const bossMoves=[['躲开冲撞','拉紧鱼线'],['拉住背鳍','松线卸力'],['拖向浅滩','躲开摆尾']];const bossRight=[0,0,1];
function showBoss(){let b=islands[S.island];let stage=bossRound;let req=S.island===0?S.items.木料>=2&&S.items.绳索>=1:S.island===1?S.rod>=1&&(S.fish['灯笼鱼']||0)>=1:S.rod>=2&&(S.fish['雷纹鲹']||0)>=1;let actions=bossMoves[Math.min(stage,2)];let roundText=stage>=3?'挑战完成！':`第 ${stage+1} / 3 回合：${['它正朝小船冲来！','它露出背鳍，机会来了！','它开始猛烈摆尾！'][stage]}`;if(!req&&stage===0){let need=S.island===0?'修船准备：木料 2、绳索 1':S.island===1?'准备远海线组，并钓到 1 条灯笼鱼':'升级远海钓竿，并钓到 1 条雷纹鲹';openSheet(`<h2>启航准备</h2><p class="sheet-sub">${need}。先去钓鱼、交易和整理装备，再回来挑战守岛巨兽。</p><div class="boss-scene"><div class="boss-emoji">🛠️</div><div class="boss-title">跟 ${b.npc} 做好出海准备</div><div class="boss-text">卖鱼能攒金币，直接换物资能加快修船。</div></div><button class="sheet-cta" onclick="openTrade()">查看交易</button><button class="sheet-cta secondary" onclick="closeSheet()">回到岸边</button>`);return}openSheet(`<h2>${b.boss}</h2><p class="sheet-sub">${stage>=3?'你抓住潮汐节奏，成功守住了航道。':roundText}</p><div class="boss-scene"><div class="boss-emoji">${['🦈','🐙','🐢'][S.island]}</div><div class="boss-title">${stage>=3?'航道畅通':'守岛巨兽'}</div><div class="boss-text">${stage>=3?'附近岛民通过无线电向你道谢。海图上亮起了新的航线。':`失误容错 ${Math.max(0,2-bossMistakes)} 次 · 用判断与装备突破挑战`}</div></div>${stage>=3?`<button class="sheet-cta" onclick="bossWin()">${S.island<2?'启航前往下一座岛':'驶向救援信号'}</button>`:`<div class="boss-actions">${actions.map((a,i)=>`<button class="${i===bossRight[stage]?'good':''}" onclick="bossAct(${i})">${a}</button>`).join('')}</div>`}${stage<3?'':'<p class="sheet-sub" style="text-align:center;margin-top:10px">伙伴们已为你标记安全航线。</p>'}<button class="sheet-cta secondary" onclick="closeSheet()">稍后再战</button>`)}
function bossAct(i){let right=bossRight[bossRound];if(i!==right){bossMistakes++;if(bossMistakes>=3){toast('船体受损，退回营地休整后再来');closeSheet();S.stamina=S.maxStamina;save();return}toast('判断稍慢了些，但稳住船身还来得及')}else toast(['漂亮地避开冲撞！','鱼线勾住了！','成功把它引向浅滩！'][bossRound]);bossRound++;showBoss()}
function bossWin(){if(!S.won.includes(S.island))S.won.push(S.island);S.coins+=12;if(S.island<2){S.island++;S.stamina=S.maxStamina;S.day++;save();closeSheet();toast(`突破海域！抵达${islands[S.island].name}`)}else{S.ending=true;save();closeSheet();updateUI();openEnding()}}
function openEnding(){openSheet(`<div style="text-align:center;padding:15px 0"><div style="font-size:70px">🚢</div><h2>回家的航线</h2><p class="sheet-sub">救援船回应了你的信号。你终于能回家了。<br>一路结识的伙伴，也会在新的港口等你。</p><div class="shop-banner"><b>旅程完成</b><p>你突破了三片海域，钓获了 ${Object.keys(S.caught).length} 种海洋生物，和岛上的伙伴一起守住了航路。</p></div><button class="sheet-cta" onclick="resetGame()">再开一段旅程</button></div>`)}
function claimAd(){if(S.ads>=3){toast('今天的补给视频已经看完啦');return}openSheet(`<h2>漂流补给箱 <span class="badge">激励视频</span></h2><p class="sheet-sub">观看一段短片后可领取补给。本原型不会播放真实广告。</p><div class="shop-banner"><b>补给内容</b><p>鱼饵 ×2　·　体力 +2　·　木料 ×1</p></div><button class="sheet-cta" onclick="confirmAd()">模拟观看并领取</button><button class="sheet-cta secondary" onclick="closeSheet()">暂不需要</button>`)}
function confirmAd(){S.ads++;S.items.鱼饵+=2;S.items.木料++;S.stamina=Math.min(S.maxStamina,S.stamina+2);save();closeSheet();toast('补给已放进背包，谢谢支持！')}
function openShop(){openSheet(`<h2>海岛小铺 <span class="badge">演示商店</span></h2><div class="shop-banner"><b>把旅途装点得更有自己的样子</b><p>商店内容仅作原型展示。点击购买只会显示演示成功，不会扣款。</p></div>${row('⛵','日落船帆','外观装饰，不影响钓鱼数值','¥6','演示购买','buyDemo("日落船帆")')}${row('🧢','海风渔夫帽','外观装饰，可在营地展示','¥3','演示购买','buyDemo("海风渔夫帽")')}${row('🌊','清爽航行','关闭商店页的品牌展示位','¥12','演示购买','buyDemo("清爽航行")')}<button class="sheet-cta secondary" onclick="closeSheet()">返回游戏</button>`)}
function buyDemo(x){toast(`${x}：演示购买成功，没有实际扣费`)}
function showHome(){document.querySelector('#playArea').scrollIntoView({behavior:'smooth'})}
function resetGame(){localStorage.removeItem(KEY);S={...defaultState,fish:{...defaultState.fish},items:{...defaultState.items},caught:{},won:[]};mode='ready';save();closeSheet();toast('新的旅程开始了')}
updateUI();updateFishUI();

